import esbuild from "esbuild";
import process from "node:process";
import { copyFileSync } from "node:fs";
import builtins from "builtin-modules";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
If you want to view the source, please visit the github repository of this plugin.
*/
`;

const prod = process.argv[2] === "production";

// Node builtins are marked external EXCEPT `buffer`: the compiled
// libgit2-WASM glue's Basic-auth header building (`git/libgit2/http-transport.ts`'s
// `basicAuthHeader`) needs Buffer, which does not exist in the Capacitor
// webview on Obsidian mobile. `buffer` therefore resolves to the npm polyfill
// and is bundled, while `polyfill-buffer.js` is injected to satisfy bare
// global `Buffer` references (using the real Electron Buffer on desktop).
const externalBuiltins = builtins.filter((m) => m !== "buffer");

// `ws` is referenced by the compiled Emscripten glue (`tether-libgit2.js`)
// behind an `ENVIRONMENT_IS_NODE` check for its (unused here) WebSocket
// transport path — see `git/libgit2/loader.ts`'s header comment for why that
// branch never actually executes inside Obsidian (desktop is Electron's
// *renderer* process, which the compiled glue's own environment check
// excludes from "node"; mobile has no Node process at all). It still needs
// to be marked external so esbuild doesn't try to resolve/bundle a package
// that isn't (and doesn't need to be) a real dependency.
const wasmOnlyExternals = ["ws"];

/** Copies the compiled libgit2 `.wasm` binary next to `main.js` — the WASM
 * loader (`git/libgit2/loader.ts`) reads it at runtime via
 * `app.vault.adapter.readBinary` against a path derived from the plugin's
 * own `manifest.dir`, so it must ship alongside `main.js`/`manifest.json`/
 * `styles.css` in the plugin's directory (see that file's header comment for
 * the full packaging decision). */
function copyCompiledWasm() {
	copyFileSync(
		"src/git/libgit2/build/dist/tether-libgit2.wasm",
		"tether-libgit2.wasm"
	);
}

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/*",
		"@lezer/*",
		...externalBuiltins,
		...externalBuiltins.map((m) => `node:${m}`),
		...wasmOnlyExternals,
	],
	inject: ["./polyfill-buffer.js"],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	define: {
		"process.env.NODE_ENV": prod ? '"production"' : '"development"',
	},
});

if (prod) {
	await context.rebuild();
	copyCompiledWasm();
	process.exit(0);
} else {
	copyCompiledWasm();
	await context.watch();
}
