import esbuild from "esbuild";
import process from "node:process";
import builtins from "builtin-modules";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
If you want to view the source, please visit the github repository of this plugin.
*/
`;

const prod = process.argv[2] === "production";

// Node builtins are marked external EXCEPT `buffer`: the compiled
// libgit2-WASM glue's Basic-auth header building (`git/libgit2/http-transport.ts`'s
// `basicAuthHeader`) needs Buffer, which does not exist in the Capacitor
// webview on Obsidian mobile. `buffer` therefore resolves to the npm polyfill
// and is bundled, while `polyfill-buffer.js` is injected to satisfy bare
// global `Buffer` references (using the real Electron Buffer on desktop).
const externalBuiltins = builtins.filter((m) => m !== "buffer");

// `ws` is referenced by the compiled Emscripten glue (`tether-libgit2.js`)
// behind an `ENVIRONMENT_IS_NODE` check for its (unused here) WebSocket
// transport path — see `git/libgit2/loader.ts`'s header comment for why that
// branch never actually executes inside Obsidian (desktop is Electron's
// *renderer* process, which the compiled glue's own environment check
// excludes from "node"; mobile has no Node process at all). It still needs
// to be marked external so esbuild doesn't try to resolve/bundle a package
// that isn't (and doesn't need to be) a real dependency.
const wasmOnlyExternals = ["ws"];

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/*",
		"@lezer/*",
		...externalBuiltins,
		...externalBuiltins.map((m) => `node:${m}`),
		...wasmOnlyExternals,
	],
	inject: ["./polyfill-buffer.js"],
	// The compiled libgit2 binary is embedded in main.js as base64 rather than
	// shipped beside it: Obsidian's installer and BRAT only ever fetch
	// manifest.json, main.js and styles.css from a release. See
	// src/git/libgit2/wasm-binary.ts.
	loader: {
		".wasm": "base64",
	},
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	define: {
		"process.env.NODE_ENV": prod ? '"production"' : '"development"',
	},
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
